# Generated by Django 5.1.1 on 2024-09-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('restaurant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotels.restaurant')),
                ('food_name', models.CharField(max_length=20)),
                ('food_photo', models.ImageField(upload_to='images/')),
            ],
            bases=('hotels.restaurant',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('restaurant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotels.restaurant')),
                ('servivice_name', models.CharField(max_length=20)),
                ('service_price', models.IntegerField()),
            ],
            bases=('hotels.restaurant',),
        ),
    ]
