# Generated by Django 5.1.1 on 2024-09-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_food_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='servivice_name',
            new_name='service_name',
        ),
        migrations.AddField(
            model_name='food',
            name='food_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.IntegerField(null=True),
        ),
    ]
